/*
 * File: app/controller/BatchController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.BatchController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'Batch',
        'Country',
        'Item'
    ],
    stores: [
        'BatchStore',
        'CountryStore',
        'ItemStore'
    ],
    views: [
        'BatchView'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'batchview #grid'
        },
        {
            ref: 'mainForm',
            selector: 'batchview #form'
        }
    ],

    init: function(application) {
        this.control({
            'batchview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreate
            },
            'batchview #index commonindextoolbar commonshowbtn':{
                click:this.doShow
            },
            'batchview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'batchview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'batchview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },
            'batchview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShow
            }

        });

        this.domainName = 'batch';
    }

});
