/*
 * File: app/controller/BatchRouteController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.BatchRouteController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'BatchRotue',
        'Batch',
        'Operation',
        'Workstation'
    ],
    stores: [
        'OperationStore',
        'WorkstationStore',
        'BatchStore',
        'BatchRouteStore'
    ],
    views: [
        'BatchRouteView'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'batchrouteview #grid'
        },
        {
            ref: 'mainForm',
            selector: 'batchrouteview #form'
        },
        {
            ref: 'masterGrid',
            selector: 'batchrouteview #masterGrid'
        }
    ],

    init: function(application) {
        this.control({
            'batchrouteview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreate
            },
            'batchrouteview #index commonindextoolbar commonshowbtn':{
                click:this.doShowBatchRoute
            },
            'batchrouteview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'batchrouteview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'batchrouteview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },

            'batchrouteview #index #masterGrid':{
                select:this.doIndexDetail
            },
            'batchrouteview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShowBatchRoute
            }
        });


        this.domainName = 'batchRoute';
        this.masterKey='batch.id';
    },

    doShowBatchRoute: function() {
        this.doShow(function(success,form,action){
            //由於store設定load第1-50筆
            //導致doShow時若資料屬於第50筆之後無法正常顯示
            //在此使combo重新load store
            var wscombo=form.findField('workstation.id');
            Utilities.comboReload(wscombo,action.result.data['workstation.id'],action.result.data['workstation.name']);
            var opcombo=form.findField('operation.id');
            Utilities.comboReload(opcombo,action.result.data['operation.id'],action.result.data['operation.name']);
            var spcombo=form.findField('supplier.id');
            Utilities.comboReload(spcombo,action.result.data['supplier.id'],action.result.data['supplier.name']);

        });
    }

});
