/*
 * File: app/controller/ErpMaterialReturnSheetController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.ErpMaterialReturnSheetController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'ErpMaterialReturnSheet'
    ],
    stores: [
        'ErpMaterialReturnSheetStore'
    ],
    views: [
        'ErpMaterialReturnSheetView'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'erpmaterialreturnsheetview #grid'
        },
        {
            ref: 'mainForm',
            selector: 'erpmaterialreturnsheetview #form'
        },
        {
            ref: 'detailGrid',
            selector: 'erpmaterialreturnsheetview #detailGrid'
        },
        {
            ref: 'detailForm',
            selector: 'erpmaterialreturnsheetview #detailForm'
        }
    ],

    init: function(application) {
        this.control({
            'erpmaterialreturnsheetview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreateAndIndexDetail
            },
            'erpmaterialreturnsheetview #index commonindextoolbar commonshowbtn':{
                click:this.doShowMaterialSheet
            },
            'erpmaterialreturnsheetview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'erpmaterialreturnsheetview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'erpmaterialreturnsheetview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },
            'erpmaterialreturnsheetview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShowMaterialSheet
            },
            'erpmaterialreturnsheetview #show commonindextoolbar commoncreatebtn':{
                click:this.doCreateDetail
            },
            'erpmaterialreturnsheetview #show commonindextoolbar commonshowbtn':{
                click:this.doShowMaterialSheetDet
            },
            'erpmaterialreturnsheetview #showDetail commonshowtoolbar commondeletebtn':{
                click:this.doDeleteDetail
            },
            'erpmaterialreturnsheetview #showDetail commonshowtoolbar commonsavebtn':{
                click:this.doSaveDetail
            },
            'erpmaterialreturnsheetview #showDetail commonshowtoolbar commoncancelbtn':{
                click:this.doCancelDetail
            },
            'erpmaterialreturnsheetview #detailGrid':{
                select: this.enableDetailShowBtn,
                deselect: this.disableDetailShowBtn,
                itemdblclick: this.doShowMaterialSheetDet
            },
            'erpmaterialreturnsheetview #showDetail commonselectbtn':{
                click:this.activeManufactureOrderIndex
            },
            'erpmaterialreturnsheetview #manufactureOrderIndex erpmanufactureordergrid':{
                itemdblclick: this.doSelectManufactureOrder
            }

        });


        this.domainName = 'foodpaint';
        this.foodpaintController = 'materialReturnSheet';
        this.foodpaintDetController = 'materialReturnSheetDet';
        this.masterKey='materialReturnSheet.id';
    },

    doSelectManufactureOrder: function(obj, record, index, eOpts) {
        this.getDetailForm().getForm().setValues({

            'manufactureOrder.id':record.data['id'],
            'manufactureOrder.typeName':record.data['typeName'],
            'manufactureOrder.name':record.data['name']
        });
        this.activeDetailEditor();
    },

    doShowMaterialReturnSheet: function() {
        this.doShowAndIndexDetail(function(success,form,action){
            //由於store設定load第1-50筆
            //導致doShow時若資料屬於第50筆之後無法正常顯示
            //在此使combo重新load store
            var wscombo=form.findField('workstation.id');
            Utilities.comboReload(wscombo,action.result.data['workstation.id'],action.result.data['workstation.name']);
            var spcombo=form.findField('supplier.id');
            Utilities.comboReload(spcombo,action.result.data['supplier.id'],action.result.data['supplier.name']);
        });
    },

    doShowMaterialReturnSheetDet: function() {
        this.doShowDetail(function(success,form,action){
            //由於store設定load第1-50筆
            //導致doShow時若資料屬於第50筆之後無法正常顯示
            //在此使combo重新load store
            var batchcombo=form.findField('batch.id');
            Utilities.comboReload(batchcombo,action.result.data['batch.id'],action.result.data['batch.name']);
        });
    }

});
