/*
 * File: app/controller/ErpPurchaseSheetController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.ErpPurchaseSheetController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'ErpPurchaseSheet'
    ],
    stores: [
        'ErpPurchaseSheetStore'
    ],
    views: [
        'ErpPurchaseSheetView'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'erppurchasesheetview #grid'
        },
        {
            ref: 'mainForm',
            selector: 'erppurchasesheetview #form'
        },
        {
            ref: 'detailGrid',
            selector: 'erppurchasesheetview #detailGrid'
        },
        {
            ref: 'detailForm',
            selector: 'erppurchasesheetview #detailForm'
        }
    ],

    init: function(application) {
        this.control({
            'erppurchasesheetview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreateAndIndexDetail
            },
            'erppurchasesheetview #index commonindextoolbar commonshowbtn':{
                click:this.doShowAndIndexDetail
            },
            'erppurchasesheetview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'erppurchasesheetview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'erppurchasesheetview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },
            'erppurchasesheetview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShowAndIndexDetail
            },
            'erppurchasesheetview #show commonindextoolbar commoncreatebtn':{
                click:this.doCreateDetail
            },
            'erppurchasesheetview #show commonindextoolbar commonshowbtn':{
                click:this.doShowDetail
            },
            'erppurchasesheetview #showDetail commonshowtoolbar commondeletebtn':{
                click:this.doDeleteDetail
            },
            'erppurchasesheetview #showDetail commonshowtoolbar commonsavebtn':{
                click:this.doSaveDetail
            },
            'erppurchasesheetview #showDetail commonshowtoolbar commoncancelbtn':{
                click:this.doCancelDetail
            },
            'erppurchasesheetview #detailGrid':{
                select: this.enableDetailShowBtn,
                deselect: this.disableDetailShowBtn,
                itemdblclick: this.doShowDetail
            }

        });


        this.domainName = 'foodpaint';
        this.foodpaintController = 'purchaseSheet';
        this.foodpaintDetController = 'purchaseSheetDet';
        this.masterKey='purchaseSheet.id';
    }

});
