/*
 * File: app/controller/ErpPurchaseReturnSheetController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.ErpPurchaseReturnSheetController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'ErpPurchaseReturnSheet',
        'ErpPurchaseReturnSheetDet'
    ],
    stores: [
        'ErpPurchaseReturnSheetDetStore',
        'ErpSaleReturnSheetDetStore'
    ],
    views: [
        'ErpPurchaseReturnSheetView'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'erppurchasereturnsheetview #grid'
        },
        {
            ref: 'mainForm',
            selector: 'erppurchasereturnsheetview #form'
        },
        {
            ref: 'detailGrid',
            selector: 'erppurchasereturnsheetview #detailGrid'
        },
        {
            ref: 'detailForm',
            selector: 'erppurchasereturnsheetview #detailForm'
        }
    ],

    init: function(application) {
        this.control({
            'erppurchasereturnsheetview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreateAndIndexDetail
            },
            'erppurchasereturnsheetview #index commonindextoolbar commonshowbtn':{
                click:this.doShowPurchaseReturnSheet
            },
            'erppurchasereturnsheetview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'erppurchasereturnsheetview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'erppurchasereturnsheetview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },
            'erppurchasereturnsheetview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShowPurchaseReturnSheet
            },
            'erppurchasereturnsheetview #show commonindextoolbar commoncreatebtn':{
                click:this.doCreateDetail
            },
            'erppurchasereturnsheetview #show commonindextoolbar commonshowbtn':{
                click:this.doShowPurchaseSheetDet
            },
            'erppurchasereturnsheetview #showDetail commonshowtoolbar commondeletebtn':{
                click:this.doDeleteDetail
            },
            'erppurchasereturnsheetview #showDetail commonshowtoolbar commonsavebtn':{
                click:this.doSaveDetail
            },
            'erppurchasereturnsheetview #showDetail commonshowtoolbar commoncancelbtn':{
                click:this.doCancelDetail
            },
            'erppurchasereturnsheetview #detailGrid':{
                select: this.enableDetailShowBtn,
                deselect: this.disableDetailShowBtn,
                itemdblclick: this.doShowPurchaseReturnSheetDet
            }

        });


        this.domainName = 'foodpaint';
        this.foodpaintController = 'purchaseReturnSheet';
        this.foodpaintDetController = 'purchaseReturnSheetDet';
        this.masterKey='purchaseReturnSheet.id';
    },

    doShowPurchaseReturnSheet: function() {
        this.doShowAndIndexDetail(function(success,form,action){
            //由於store設定load第1-50筆
            //導致doShow時若資料屬於第50筆之後無法正常顯示
            //在此使combo重新load store
            var spcombo=form.findField('supplier.id');
            Utilities.comboReload(spcombo,action.result.data['supplier.id'],action.result.data['supplier.name']);

        });
    },

    doShowPurchaseReturnSheetDet: function() {

        this.doShowDetail(function(success,form,action){
            //由於store設定load第1-50筆
            //導致doShow時若資料屬於第50筆之後無法正常顯示
            //在此使combo重新load store
            var itemcombo=form.findField('item.id');
            Utilities.comboReload(itemcombo,action.result.data['item.id'],action.result.data['item.name']);

            var whcombo=form.findField('warehouse.id');
            Utilities.comboReload(whcombo,action.result.data['warehouse.id'],action.result.data['warehouse.name']);

            //warehouseLocation combo需指定warehouse id才可load
            var wlcombo=form.findField('warehouseLocation.id');
            Utilities.compositionComboReload(wlcombo, 'warehouse.id', action.result.data['warehouse.id'],action.result.data['warehouseLocation.id']);
        });
    }

});
