/*
 * File: app/controller/ErpSaleSheetController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.ErpSaleSheetController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'ErpSaleSheet'
    ],
    stores: [
        'ErpSaleSheetStore'
    ],
    views: [
        'ErpSaleSheetView'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'erpsalesheetview #grid'
        },
        {
            ref: 'mainForm',
            selector: 'erpsalesheetview #form'
        }
    ],

    init: function(application) {
        this.control({
            'erpsalesheetview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreate
            },
            'erpsalesheetview #index commonindextoolbar commonshowbtn':{
                click:this.doShow
            },
            'erpsalesheetview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'erpsalesheetview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'erpsalesheetview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },
            'erpsalesheetview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShow
            }

        });


        this.domainName = 'foodpaint';
        this.foodpaintController = 'saleSheet';
    }

});
