/*
 * File: app/controller/ErpSaleReturnSheetController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.ErpSaleReturnSheetController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'ErpSaleReturnSheet'
    ],
    stores: [
        'ErpSaleReturnSheetStore'
    ],
    views: [
        'ErpSaleReturnSheetView'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'erpsalereturnsheetvie #grid'
        },
        {
            ref: 'mainForm',
            selector: 'erpsalereturnsheetview #form'
        },
        {
            ref: 'detailGrid',
            selector: 'erpsalereturnsheetview #detailgrid'
        },
        {
            ref: 'detailForm',
            selector: 'erpsalereturnsheetview #detailform'
        }
    ],

    init: function(application) {
        this.control({
            'erpsalereturnsheetview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreateAndIndexDetail
            },
            'erpsalereturnsheetview #index commonindextoolbar commonshowbtn':{
                click:this.doShowSaleSheet
            },
            'erpsalereturnsheetview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'erpsalereturnsheetview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'erpsalereturnsheetview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },
            'erpsalereturnsheetview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShowSaleSheet
            },
            'erpsalereturnsheetview #show commonindextoolbar commoncreatebtn':{
                click:this.doCreateDetail
            },
            'erpsalereturnsheetview #show commonindextoolbar commonshowbtn':{
                click:this.doShowSaleSheetDet
            },
            'erpsalereturnsheetview #showDetail commonshowtoolbar commondeletebtn':{
                click:this.doDeleteDetail
            },
            'erpsalereturnsheetview #showDetail commonshowtoolbar commonsavebtn':{
                click:this.doSaveDetail
            },
            'erpsalereturnsheetview #showDetail commonshowtoolbar commoncancelbtn':{
                click:this.doCancelDetail
            },
            'erpsalereturnsheetview #detailGrid':{
                select: this.enableDetailShowBtn,
                deselect: this.disableDetailShowBtn,
                itemdblclick: this.doShowSaleSheetDet
            },
            'erpsalereturnsheetview #showDetail commonselectbtn':{
                click:this.activeCustomerOrderDetIndex
            },
            'erpsalereturnsheetview #customerOrderDetIndex erpcustomerordergrid':{
                select: this.doIndexDetailCustomerOrder
            },
            'erpsalereturnsheetview #customerOrderDetIndex erpcustomerorderdetgrid':{
                itemdblclick: this.doSelectCustomerOrderDet
            }

        });


        this.domainName = 'foodpaint';
        this.foodpaintController = 'saleReturnSheet';
        this.foodpaintDetController = 'saleReturnSheetDet';
        this.masterKey='saleReturnSheet.id';
    },

    doIndexDetailCustomerOrder: function() {
        this.getDetailForm().getForm().setValues({

            'customerOrderDet.id':record.data['id'],
            'customerOrderDet.typeName':record.data['typeName'],
            'customerOrderDet.name':record.data['name'],
            'customerOrderDet.sequence':record.data['sequence'],
            'item.id':record.data['item.id'],
            'item.title':record.data['item.title'],
            'qty':record.data['qty']
        });
        this.reloadBatchComboByItem(record.data['item.id']);
        this.activeDetailEditor();
    },

    doSelectCustomerOrderDet: function() {
        this.getDetailForm().getForm().setValues({

            'customerOrderDet.id':record.data['id'],
            'customerOrderDet.typeName':record.data['typeName'],
            'customerOrderDet.name':record.data['name'],
            'customerOrderDet.sequence':record.data['sequence'],
            'item.id':record.data['item.id'],
            'item.title':record.data['item.title'],
            'qty':record.data['qty']
        });
        this.reloadBatchComboByItem(record.data['item.id']);
        this.activeDetailEditor();
    },

    doShowSaleReturnSheet: function() {
        this.doShowAndIndexDetail(function(success,form,action){
            //由於store設定load第1-50筆
            //導致doShow時若資料屬於第50筆之後無法正常顯示
            //在此使combo重新load store
            var cucombo=form.findField('customer.id');
            Utilities.comboReload(cucombo,action.result.data['customer.id'],action.result.data['customer.name']);

        });
    },

    doShowSaleReturnSheetDet: function() {
        this.doShowDetail(function(success,form,action){
            //由於store設定load第1-50筆
            //導致doShow時若資料屬於第50筆之後無法正常顯示
            //在此使combo重新load store
            var whcombo=form.findField('warehouse.id');
            Utilities.comboReload(whcombo,action.result.data['warehouse.id'],action.result.data['warehouse.name']);
            var batchcombo=form.findField('batch.id');
            Utilities.comboReload(batchcombo,action.result.data['batch.id'],action.result.data['batch.name']);
            var itemcombo=form.findField('item.id');
            Utilities.comboReload(itemcombo,action.result.data['item.id'],action.result.data['item.name']);
        });
    }

});
