/*
 * File: app/controller/ErpSaleSheetDetController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.ErpSaleSheetDetController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'ErpSaleSheetDet',
        'ErpSaleSheet'
    ],
    stores: [
        'ErpSaleSheetDetStore',
        'ErpSaleSheetStore'
    ],
    views: [
        'ErpSaleSheetDetView'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'erpsalesheetdetview #grid'
        },
        {
            ref: 'mainForm',
            selector: 'erpsalesheetdetview #form'
        },
        {
            ref: 'masterGrid',
            selector: 'erpsalesheetdetview #masterGrid'
        }
    ],

    init: function(application) {

        this.control({
            'erpsalesheetdetview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreate
            },
            'erpsalesheetdetview #index commonindextoolbar commonshowbtn':{
                click:this.doShow
            },
            'erpsalesheetdetview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'erpsalesheetdetview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'erpsalesheetdetview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },
            'erpsalesheetdetview #index #masterGrid':{
                select:this.doIndexDetail
            },
            'erpsalesheetdetview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShow
            }
        });

        this.domainName = 'foodpaint';
        this.foodpaintController = 'saleSheetDet';
        this.masterKey='saleSheet.id';

    }

});
