/*
 * File: app/controller/ErpSaleSheetDetController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.ErpSaleSheetDetController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'ErpSaleSheetDet',
        'ErpSaleSheet'
    ],
    stores: [
        'ErpSaleSheetDetStore',
        'ErpSaleSheetStore'
    ],
    views: [
        'ErpSaleSheetDetView'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'erpsalesheetdetview #grid'
        },
        {
            ref: 'mainForm',
            selector: 'erpsalesheetdetview #form'
        },
        {
            ref: 'masterGrid',
            selector: 'erpsalesheetdetview #masterGrid'
        }
    ],

    init: function(application) {

        this.control({
            'erpsalesheetdetview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreate
            },
            'erpsalesheetdetview #index commonindextoolbar commonshowbtn':{
                click:this.doShow
            },
            'erpsalesheetdetview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'erpsalesheetdetview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'erpsalesheetdetview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },
            'erpsalesheetdetview #index #masterGrid':{
                select:this.doIndexDetail
            },
            'erpsalesheetdetview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShow
            },
            'erpsalesheetdetview #show commonselectbtn':{
                click:this.activeCustomerOrderDetIndex
            },
            'erpsalesheetdetview #customerOrderDetIndex erpcustomerordergrid':{
                select: this.doIndexDetailCustomerOrder
            },
            'erpsalesheetdetview #customerOrderDetIndex erpcustomerorderdetgrid':{
                itemdblclick: this.doSelectCustomerOrderDet
            }
        });

        this.domainName = 'foodpaint';
        this.foodpaintController = 'saleSheetDet';
        this.masterKey='saleSheet.id';

    },

    doIndexDetailCustomerOrder: function(obj, record, index, eOpts) {
        var grid = this.getMainGrid().up().up().down("panel[itemId=customerOrderDetIndex]").down("grid[itemId=erpCustomerOrderDetGrid]");

        grid.getStore().data.clear();

        var params = {}
        params["customerOrder.id"]=record.data.id;

        grid.getStore().getProxy().extraParams = params;
        grid.getStore().load();
    },

    doSelectCustomerOrderDet: function(obj, record, index, eOpts) {
        this.getMainForm().getForm().setValues({

            'customerOrderDet.id':record.data['id'],
            'customerOrderDet.typeName':record.data['typeName'],
            'customerOrderDet.name':record.data['name'],
            'customerOrderDet.sequence':record.data['sequence'],
            'item.id':record.data['item.id'],
            'item.name':record.data['item.name'],
            'item.title':record.data['item.title'],
            'qty':record.data['qty']
        });
        this.reloadBatchComboByItem(record.data['item.id']);
        this.activeEditor();
    },

    reloadBatchComboByItem: function(itemId) {
        var combo = this.getMainForm().down("combo[itemId=commonBatchCombo]");
        combo.getStore().load({
            url:'/batch/indexByItem',
            params: {'item.id': itemId}
        });
        //combo在remote模式下
        //設定第一次trigger時自動load
        //造成此處指定查詢的Batch結果會被覆蓋
        //給定lastQuery使系統默認為已load過
        combo.lastQuery='';
    }

});
