/*
 * File: app/controller/ErpSaleReturnSheetController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.ErpSaleReturnSheetController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'ErpSaleReturnSheet',
        'ErpSaleReturnSheetDet',
        'ErpSaleSheet',
        'ErpSaleSheetDet',
        'Customer',
        'Warehouse',
        'WarehouseLocation'
    ],
    stores: [
        'ErpSaleReturnSheetStore',
        'ErpSaleReturnSheetDetStore',
        'ErpSaleSheetStore',
        'ErpSaleSheetDetStore',
        'CustomerStore',
        'WarehouseStore',
        'WarehouseLocationStore'
    ],
    views: [
        'ErpSaleReturnSheetView'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'erpsalereturnsheetview #grid'
        },
        {
            ref: 'mainForm',
            selector: 'erpsalereturnsheetview #form'
        },
        {
            ref: 'detailGrid',
            selector: 'erpsalereturnsheetview #detailGrid'
        },
        {
            ref: 'detailForm',
            selector: 'erpsalereturnsheetview #detailForm'
        }
    ],

    init: function(application) {
        this.control({
            'erpsalereturnsheetview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreateAndIndexDetail
            },
            'erpsalereturnsheetview #index commonindextoolbar commonshowbtn':{
                click:this.doShowSaleReturnSheet
            },
            'erpsalereturnsheetview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'erpsalereturnsheetview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'erpsalereturnsheetview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },
            'erpsalereturnsheetview #show commonshowtoolbar commonprintbtn':{
                click:this.doPrint
            },
            'erpsalereturnsheetview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShowSaleReturnSheet
            },
            'erpsalereturnsheetview #show commonindextoolbar commoncreatebtn':{
                click:this.doCreateSaleReturnSheetDet
            },
            'erpsalereturnsheetview #show commonindextoolbar commonshowbtn':{
                click:this.doShowSaleReturnSheetDet
            },
            'erpsalereturnsheetview #showDetail commonshowtoolbar commondeletebtn':{
                click:this.doDeleteDetail
            },
            'erpsalereturnsheetview #showDetail commonshowtoolbar commonsavebtn':{
                click:this.doSaveDetail
            },
            'erpsalereturnsheetview #showDetail commonshowtoolbar commoncancelbtn':{
                click:this.doCancelDetail
            },
            'erpsalereturnsheetview #detailGrid':{
                select: this.enableDetailShowBtn,
                deselect: this.disableDetailShowBtn,
                itemdblclick: this.doShowSaleReturnSheetDet
            },
            'erpsalereturnsheetview #showDetail #saleSheetDetContainer commonselectbtn':{
                click:this.activeSaleSheetDetIndex
            },
            'erpsalereturnsheetview #saleSheetDetIndex erpsalesheetgrid':{
                select: this.doIndexDetailSaleSheet
            },
            'erpsalereturnsheetview #saleSheetDetIndex erpsalesheetdetgrid':{
                itemdblclick: this.doSelectSaleSheetDet
            }

        });

        this.domainName = 'foodpaint';
        this.foodpaintController = 'saleReturnSheet';
        this.foodpaintDetController = 'saleReturnSheetDet';
        this.masterKey='saleReturnSheet.id';
    },

    doShowSaleReturnSheet: function() {
        this.doShowAndIndexDetail(function(success,form,action){
            //由於store設定load第1-50筆
            //導致doShow時若資料屬於第50筆之後無法正常顯示
            //在此使combo重新load store
            var cucombo=form.findField('customer.id');
            Utilities.comboReload(cucombo,action.result.data['customer.id'],action.result.data['customer.name']);

        });
    },

    doCreateSaleReturnSheetDet: function() {
        var that=this;
        this.doCreateDetail(function(success,form,action){

            //篩選出客戶符合的銷貨單
            that.reloadSaleSheetByCustomer(action.result.data.saleReturnSheet.customer.id);
        });
    },

    doShowSaleReturnSheetDet: function() {
        var that=this;
        this.doShowDetail(function(success,form,action){
            //由於store設定load第1-50筆
            //導致doShow時若資料屬於第50筆之後無法正常顯示
            //在此使combo重新load store
            var whcombo=form.findField('warehouse.id');
            Utilities.comboReload(whcombo,action.result.data['warehouse.id'],action.result.data['warehouse.name']);

            //warehouseLocation combo需指定warehouse id才可load
            var wlcombo=form.findField('warehouseLocation.id');
            Utilities.compositionComboReload(wlcombo, 'warehouse.id', action.result.data['warehouse.id'],action.result.data['warehouseLocation.id']);

            //篩選出客戶符合的銷貨單
            that.reloadSaleSheetByCustomer(action.result.data.saleReturnSheet.customer.id);
        });
    },

    reloadSaleSheetByCustomer: function(customerId) {
        //重新load篩選出符合的銷貨單

        var grid = this.getMainGrid().up().up().down("panel[itemId=saleSheetDetIndex]").down("grid[itemId=erpSaleSheetGrid]");
        var detailGrid=this.getMainGrid().up().up().down("panel[itemId=saleSheetDetIndex]").down("grid[itemId=erpSaleSheetDetGrid]");

        grid.getStore().removeAll();
        grid.getStore().load({
            url:'/foodpaint/action?foodpaintController=saleSheet&foodpaintAction=indexByCustomer/',
            params: {'customer.id': customerId}
        });

        detailGrid.getStore().removeAll();
    },

    activeSaleSheetDetIndex: function() {

        this.getMainForm().up('panel[itemId=show]').up().getLayout().setActiveItem(this.getMainGrid().up().up().down("panel[itemId=saleSheetDetIndex]"));

    },

    doIndexDetailSaleSheet: function(obj, record, index, eOpts) {
        var grid = this.getMainGrid().up().up().down("panel[itemId=saleSheetDetIndex]").down("grid[itemId=erpSaleSheetDetGrid]");

        grid.getStore().data.clear();

        var params = {}
        params["saleSheet.id"]=record.data.id;

        grid.getStore().getProxy().extraParams = params;
        grid.getStore().load();
    },

    doSelectSaleSheetDet: function(obj, record, index, eOpts) {
        this.getDetailForm().getForm().setValues({

            'saleSheetDet.id':record.data['id'],
            'saleSheetDet.typeName':record.data['typeName'],
            'saleSheetDet.name':record.data['name'],
            'saleSheetDet.sequence':record.data['sequence'],
            'customerOrderDet.id':record.data['customerOrderDet.id'],
            'customerOrderDet.typeName':record.data['customerOrderDet.typeName'],
            'customerOrderDet.name':record.data['customerOrderDet.name'],
            'customerOrderDet.sequence':record.data['customerOrderDet.sequence'],
            'warehouse.id':record.data['warehouse.id'],
            'warehouse.title':record.data['warehouse.title'],
            'warehouseLocation.id':record.data['warehouseLocation.id'], 
            'warehouseLocation.title':record.data['warehouseLocation.title'],   
            'item.id':record.data['item.id'],
            'item.name':record.data['item.name'],
            'item.title':record.data['item.title'],
            'batch.id':record.data['batch.id'],
            'batch.name':record.data['batch.name'],
            'qty':record.data['qty']
        });


        //在此使combo重新load store
        var whcombo=this.getDetailForm().getForm().findField('warehouse.id');
        Utilities.comboReload(whcombo,record.data['warehouse.id'],record.data['warehouse.name']);

        //warehouseLocation combo需指定warehouse id才可load
        var wlcombo=this.getDetailForm().getForm().findField('warehouseLocation.id');
        Utilities.compositionComboReload(wlcombo, 'warehouse.id',record.data['warehouse.id'],record.data['warehouseLocation.id']);

        this.activeDetailEditor();
    }

});
