/*
 * File: app/controller/ItemRouteController.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.controller.ItemRouteController', {
    extend: 'Ext.app.Controller',

    mixins: {
        commonController: 'foodprint.controller.CommonController'
    },

    models: [
        'ItemRoute',
        'Workstation',
        'Supplier',
        'Operation'
    ],
    stores: [
        'ItemRouteStore',
        'WorkstationStore',
        'SupplierStore',
        'OperationStore'
    ],
    views: [
        'ItemRouteView',
        'ItemGrid'
    ],

    refs: [
        {
            ref: 'mainGrid',
            selector: 'itemrouteview #grid'
        },
        {
            ref: 'mainForm',
            selector: 'itemrouteview #form'
        },
        {
            ref: 'masterGrid',
            selector: 'itemrouteview #masterGrid'
        }
    ],

    init: function(application) {
        this.control({
            'itemrouteview #index commonindextoolbar commoncreatebtn':{
                click:this.doCreate
            },
            'itemrouteview #index commonindextoolbar commonshowbtn':{
                click:this.doShowItemRoute
            },
            'itemrouteview #show commonshowtoolbar commondeletebtn':{
                click:this.doDelete
            },
            'itemrouteview #show commonshowtoolbar commonsavebtn':{
                click:this.doSave
            },
            'itemrouteview #show commonshowtoolbar commoncancelbtn':{
                click:this.doCancel
            },

            'itemrouteview #index #masterGrid':{
                select:this.doIndexDetail
            },
            'itemrouteview #grid':{
                select: this.enableShowBtn,
                deselect: this.disableShowBtn,
                itemdblclick: this.doShowItemRoute
            }
        });


        this.domainName = 'itemRoute';
        this.masterKey='item.id';
    },

    doShowItemRoute: function() {
        this.doShow(function(success,form,action){
            //由於store設定load第1-50筆
            //導致doShow時若資料屬於第50筆之後無法正常顯示
            //在此使combo重新load store
            var wscombo=form.findField('workstation.id');
            Utilities.comboReload(wscombo,action.result.data['workstation.id'],action.result.data['workstation.name']);
            var opcombo=form.findField('operation.id');
            Utilities.comboReload(opcombo,action.result.data['operation.id'],action.result.data['operation.name']);
            var spcombo=form.findField('supplier.id');
            Utilities.comboReload(spcombo,action.result.data['supplier.id'],action.result.data['supplier.name']);

        });


    }

});
