/*
 * File: app/store/BatchRouteParamsFormStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprintTouch.store.BatchRouteParamsFormStore', {
    extend: 'Ext.data.Store',

    requires: [
        'foodprintTouch.model.BatchReportDetDeep'
    ],

    config: {
        model: 'foodprintTouch.model.BatchReportDetDeep',
        storeId: 'BatchRouteParamsFormStore',
        proxy: {
            type: 'rest',
            url: '/batchReportDet/showBatchRouteParams',
            reader: {
                type: 'json',
                messageProperty: 'message',
                rootProperty: 'data'
            }
        }
    }
});