/*
 * File: app/store/ItemRouteStore.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprintTouch.store.ItemRouteStore', {
    extend: 'Ext.data.Store',

    requires: [
        'foodprintTouch.model.ItemRoute'
    ],

    config: {
        data: [
            {
                id: 0,
                title: '無作業收集'
            },
            {
                id: 1,
                title: '撥種'
            },
            {
                id: 2,
                title: '澆水'
            },
            {
                id: 3,
                title: '收成'
            }
        ],
        model: 'foodprintTouch.model.ItemRoute',
        storeId: 'itemRouteStore',
        proxy: {
            type: 'memory',
            reader: {
                type: 'json'
            }
        },
        fields: [
            {
                name: 'title'
            }
        ]
    }
});