/*
 * File: app/model/BatchSource.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.model.BatchSource', {
    extend: 'Ext.data.Model',

    uses: [
        'foodprint.model.Batch'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'batch.id'
        },
        {
            name: 'childBatch.id'
        },
        {
            name: 'batch.name'
        },
        {
            name: 'childBatch.name'
        },
        {
            name: 'batch.item.id'
        },
        {
            name: 'childBatch.item.id'
        },
        {
            name: 'batch.item.name'
        },
        {
            name: 'childBatch.item.name'
        },
        {
            name: 'batch.item.title'
        },
        {
            name: 'childBatch.item.title'
        },
        {
            name: 'batch.item.spec'
        },
        {
            name: 'childBatch.item.spec'
        },
        {
            name: 'batch.item.unit'
        },
        {
            name: 'childBatch.item.unit'
        },
        {
            name: 'batch.item.description'
        },
        {
            name: 'childBatch.item.description'
        },
        {
            name: 'batch.country'
        },
        {
            name: 'childBatch.country'
        },
        {
            name: 'batch.countryTitle'
        },
        {
            name: 'childBatch.countryTitle'
        },
        {
            name: 'batch.supplier.id'
        },
        {
            name: 'childBatch.supplier.id'
        },
        {
            name: 'batch.supplier.name'
        },
        {
            name: 'childBatch.supplier.name'
        },
        {
            name: 'batch.supplier.title'
        },
        {
            name: 'childBatch.supplier.title'
        },
        {
            name: 'batch.dueDate',
            type: 'date'
        },
        {
            name: 'childBatch.dueDate',
            type: 'date'
        },
        {
            name: 'batch.expectQty'
        },
        {
            name: 'childBatch.expectQty'
        },
        {
            name: 'batch.manufactureDate',
            type: 'date'
        },
        {
            name: 'childBatch.manufactureDate',
            type: 'date'
        },
        {
            name: 'batch.expirationDate',
            type: 'date'
        },
        {
            name: 'childBatch.expirationDate',
            type: 'date'
        },
        {
            name: 'batch.remark'
        },
        {
            name: 'childBatch.remark'
        }
    ],

    proxy: {
        type: 'rest',
        url: '/batchSource',
        reader: {
            type: 'json',
            root: 'data'
        }
    },

    belongsTo: {
        model: 'foodprint.model.Batch',
        getterName: 'getBatch'
    }
});