/*
 * File: app/model/Currency.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.model.Currency', {
    extend: 'Ext.data.Model',

    fields: [
        {
            mapping: 'id',
            name: 'id'
        },
        {
            name: 'currencyName'
        },
        {
            name: 'rate'
        }
    ],

    proxy: {
        type: 'rest',
        url: '/currency',
        reader: {
            type: 'json',
            root: 'currencyInstanceList',
            totalProperty: 'currencyInstanceTotal'
        }
    }
});