/*
 * File: app/model/MyModel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.model.MyModel', {
    extend: 'Ext.data.Model',

    fields: [
        {
            name: 'id'
        },
        {
            name: 'name'
        },
        {
            name: 'typeName'
        },
        {
            name: 'customer.id'
        },
        {
            name: 'customer.name'
        },
        {
            name: 'customer.title'
        },
        {
            name: 'documentDateCreated'
        },
        {
            name: 'status'
        },
        {
            name: 'closedCode'
        },
        {
            name: 'sequence'
        },
        {
            name: 'discount'
        },
        {
            name: 'originalAmounts'
        },
        {
            name: 'originaltax'
        },
        {
            name: 'originalTotalAmount'
        },
        {
            name: 'originalReceived'
        },
        {
            name: 'received'
        },
        {
            name: 'remark'
        },
        {
            name: 'signoff '
        }
    ],

    proxy: {
        type: 'rest',
        url: '/foodpaint?foodpaintController=accountSheet',
        reader: {
            type: 'json',
            root: 'accountSheetInstanceList',
            totalProperty: 'accountSheetInstanceTotal'
        }
    }
});