/*
 * File: app/view/BatchRouteList.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprintTouch.view.BatchRouteList', {
    extend: 'Ext.dataview.List',
    alias: 'widget.batchroutelist',

    config: {
        itemId: 'batchRouteList',
        scrollable: true,
        store: 'BatchRouteDeepStore',
        itemTpl: [
            '<div>{sequence}-{operation__title}-{workstation__title}</div>'
        ]
    },

    initialize: function() {
        this.callParent();

        this.setLoadingText(Utilities.getMsg("default.message.load"));


    }

});