/*
 * File: app/view/BatchRouteParamsPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprintTouch.view.BatchRouteParamsPanel', {
    extend: 'Ext.Panel',
    alias: 'widget.batchrouteparamspanel',

    requires: [
        'foodprintTouch.view.CommonBackToolbar',
        'foodprintTouch.view.CommonEditorToolbar',
        'foodprintTouch.view.CommonImageUploader'
    ],

    config: {
        height: 470,
        hidden: false,
        itemId: 'batchRouteParamsPanel',
        ui: '',
        hideOnMaskTap: false,
        layout: {
            type: 'vbox'
        },
        scrollable: false,
        items: [
            {
                xtype: 'commonbacktoolbar',
                itemId: 'batchRouteParamsBackToolbar'
            },
            {
                xtype: 'panel',
                height: 401,
                ui: '',
                layout: {
                    type: 'vbox'
                },
                scrollable: false,
                items: [
                    {
                        xtype: 'commoneditortoolbar'
                    },
                    {
                        xtype: 'formpanel',
                        flex: 2,
                        itemId: 'batchRouteParamsForm',
                        ui: 'dark',
                        layout: {
                            type: 'vbox'
                        },
                        scrollable: 'vertical'
                    },
                    {
                        xtype: 'commonimageuploader',
                        height: 153,
                        scrollable: false,
                        flex: 1
                    }
                ]
            }
        ]
    },

    initialize: function() {
        this.callParent();

        this.down('toolbar[itemId=batchRouteParamsBackToolbar]').setTitle(Utilities.getMsg('batchRouteParamsPanel.panel.label'));
    }

});