/*
 * File: app/view/BatchTrcRptDisplay.js
 *
 * This file was generated by Sencha Architect version 2.2.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Argicloud.view.BatchTrcRptDisplay', {
    extend: 'Ext.form.Panel',

    height: 586,
    width: 796,
    layout: {
        align: 'stretch',
        type: 'vbox'
    },
    bodyPadding: 10,
    title: 'My Form',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    flex: 1,
                    layout: {
                        align: 'stretch',
                        type: 'hbox'
                    },
                    title: '',
                    items: [
                        {
                            xtype: 'container',
                            flex: 1,
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    title: '履歷',
                                    store: 'batchTrcRptStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'title',
                                            text: 'Title'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'id',
                                            text: 'Id'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    title: '項目',
                                    store: 'BatchTrcRptRowStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'title',
                                            text: 'Title'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'description',
                                            text: 'Description'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'id',
                                            text: 'Id'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'batchTrcRpt_id',
                                            text: 'BatchTrcRpt_id'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            title: '',
                            store: 'BatchTrcRptColStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'id',
                                    text: 'Id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'BatchTrcRptRow_id',
                                    text: 'BatchTrcRptRow_id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'title',
                                    text: 'Title'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'type',
                                    text: 'Type'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'value',
                                    text: 'Value'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'description',
                                    text: 'Description'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'effectiveDate',
                                    text: 'EffectiveDate'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'expityDate',
                                    text: 'ExpityDate'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});