/*
 * File: app/view/IndTrcRptEditor.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('finder_extjs.view.IndTrcRptEditor', {
    extend: 'Ext.tab.Panel',

    requires: [
        'finder_extjs.view.ListToolbar',
        'finder_extjs.view.ImageEditorToolbar',
        'finder_extjs.view.StdEditorToolbar'
    ],

    height: 595,
    width: 722,
    activeTab: 0,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    title: '瀏覽',
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            title: '',
                            store: 'IndTrcRptStore',
                            dockedItems: [
                                {
                                    xtype: 'listtoolbar',
                                    dock: 'top',
                                    width: 100
                                }
                            ],
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'id',
                                    text: 'Id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'name',
                                    text: 'Name'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'title',
                                    text: 'Title'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'description',
                                    text: 'Description'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'note',
                                    text: 'Note'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    title: '資料維護',
                    items: [
                        {
                            xtype: 'panel',
                            flex: 1,
                            itemId: 'trcRptViewer',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            title: '',
                            items: [
                                {
                                    xtype: 'panel',
                                    layout: {
                                        align: 'stretch',
                                        padding: 10,
                                        type: 'vbox'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            flex: 1,
                                            fieldLabel: 'id',
                                            name: 'id'
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'name',
                                            name: 'title'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            fieldLabel: 'title',
                                            name: 'title'
                                        },
                                        {
                                            xtype: 'numberfield',
                                            flex: 1,
                                            fieldLabel: 'desctiption',
                                            name: 'description'
                                        },
                                        {
                                            xtype: 'textfield',
                                            flex: 1,
                                            fieldLabel: 'note',
                                            name: 'note'
                                        },
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            fieldLabel: 'effectiveDate',
                                            name: 'effectiveDate'
                                        },
                                        {
                                            xtype: 'datefield',
                                            flex: 1,
                                            fieldLabel: 'expiryDate',
                                            name: 'expiryDate'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'tabpanel',
                                    flex: 1,
                                    activeTab: 0,
                                    items: [
                                        {
                                            xtype: 'panel',
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            title: '圖檔',
                                            items: [
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    height: 250,
                                                    itemId: 'trcRptImgGrid',
                                                    width: 400,
                                                    store: 'TrcRptImg',
                                                    dockedItems: [
                                                        {
                                                            xtype: 'imageeditortoolbar',
                                                            width: 100,
                                                            dock: 'top'
                                                        }
                                                    ],
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'id',
                                                            text: 'Id'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'trc_id',
                                                            text: 'Trc_id'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            dataIndex: 'name',
                                                            text: 'Name'
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'panel',
                                            layout: {
                                                align: 'stretch',
                                                type: 'hbox'
                                            },
                                            title: '細項設定',
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    layout: {
                                                        align: 'stretch',
                                                        type: 'vbox'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'gridpanel',
                                                            flex: 1,
                                                            itemId: 'trcRptImgGrid',
                                                            title: '',
                                                            store: 'IndTrcRptRowStore',
                                                            dockedItems: [
                                                                {
                                                                    xtype: 'stdeditortoolbar',
                                                                    width: 100,
                                                                    dock: 'top'
                                                                }
                                                            ],
                                                            columns: [
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'id',
                                                                    text: 'Id'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'IndTrcRpt_id',
                                                                    text: 'IndTrcRpt_id'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'title',
                                                                    text: 'Title'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'type',
                                                                    text: 'Type'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'description',
                                                                    text: 'Description'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'effectiveDate',
                                                                    text: 'EffectiveDate'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    dataIndex: 'expiryDate',
                                                                    text: 'ExpiryDate'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'tabpanel',
                                                    flex: 1,
                                                    activeTab: 0,
                                                    items: [
                                                        {
                                                            xtype: 'panel',
                                                            layout: {
                                                                align: 'stretch',
                                                                type: 'vbox'
                                                            },
                                                            title: '欄位',
                                                            items: [
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    itemId: 'trcRptColGrid',
                                                                    title: '',
                                                                    store: 'IndTrcRptRowStore',
                                                                    dockedItems: [
                                                                        {
                                                                            xtype: 'stdeditortoolbar',
                                                                            width: 100,
                                                                            dock: 'top'
                                                                        }
                                                                    ],
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'id',
                                                                            text: 'Id'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'IndTrcRpt_id',
                                                                            text: 'IndTrcRpt_id'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'title',
                                                                            text: 'Title'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'type',
                                                                            text: 'Type'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'description',
                                                                            text: 'Description'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'effectiveDate',
                                                                            text: 'EffectiveDate'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'expiryDate',
                                                                            text: 'ExpiryDate'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'panel',
                                                            title: '圖檔',
                                                            items: [
                                                                {
                                                                    xtype: 'gridpanel',
                                                                    itemId: 'trcRptRowImgGrid',
                                                                    title: '',
                                                                    store: 'IndTrcRptRowImgStore',
                                                                    dockedItems: [
                                                                        {
                                                                            xtype: 'imageeditortoolbar',
                                                                            width: 100,
                                                                            dock: 'top'
                                                                        }
                                                                    ],
                                                                    columns: [
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'id',
                                                                            text: 'Id'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'trcRptRow_id',
                                                                            text: 'TrcRptRow_id'
                                                                        },
                                                                        {
                                                                            xtype: 'gridcolumn',
                                                                            dataIndex: 'name',
                                                                            text: 'Name'
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            dockedItems: [
                                {
                                    xtype: 'stdeditortoolbar',
                                    flex: 1,
                                    dock: 'top'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});