/*
 * File: app/view/TrcRptGrid.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('finder_extjs.view.TrcRptGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.trcrptgrid',

    height: 250,
    itemId: 'trcRptGrid',
    width: 400,
    store: 'TrcRptStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'id',
                    text: 'Id'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'Name'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'title',
                    text: 'Title'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'description',
                    text: 'Description'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'note',
                    text: 'Note'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'effectiveDate',
                    text: 'EffectiveDate'
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'expireDate',
                    text: 'ExpireDate'
                }
            ]
        });

        me.callParent(arguments);
    }

});