/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.2.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

//@require @packageOverrides
Ext.Loader.setConfig({
    paths: {
        'Ext.ux': 'ux',
        'Ext.i18n': 'ux/i18n'
    }
});

Ext.application({

    requires: [
        'foodprintTouch.view.Utilities',
        'Ext.i18n.Bundle'
    ],
    controllers: [
        'BatchParamsCarouselController',
        'MainCtController'
    ],
    name: 'foodprintTouch',

    launch: function() {
        Ext.Date.defaultFormat= 'Y-m-d';

        this.bundle = Ext.create('Ext.i18n.Bundle',{
            bundle: 'Application',
            lang: 'zh-TW',
            path: '../../i18n',
            noCache: true
        });

        Ext.create('foodprintTouch.view.MainCt', {fullscreen: true});
    }

});
