/*
 * File: app/view/BatchRouteView.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.view.BatchRouteView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.batchrouteview',

    requires: [
        'foodprint.view.BatchGrid',
        'foodprint.view.BatchRouteGrid',
        'foodprint.view.CommonOperationCombo',
        'foodprint.view.CommonWorkstationCombo',
        'foodprint.view.CommonSupplierCombo',
        'foodprint.view.CommonIndexToolbar',
        'foodprint.view.CommonShowToolbar'
    ],

    layout: {
        type: 'card'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commonindextoolbar'
                    },
                    itemId: 'index',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'batchgrid',
                            itemId: 'masterGrid',
                            autoScroll: true,
                            flex: 1
                        },
                        {
                            xtype: 'batchroutegrid',
                            itemId: 'grid',
                            autoScroll: true,
                            flex: 1
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commonshowtoolbar'
                    },
                    itemId: 'show',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        me.processForm({
                            xtype: 'form',
                            flex: 1,
                            itemId: 'form',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            bodyPadding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'batch.id',
                                    name: 'batch.id',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    hidden: true,
                                    fieldLabel: 'id',
                                    name: 'id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'numberfield',
                                    fieldLabel: 'sequence',
                                    name: 'sequence',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'commonoperationcombo'
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    fieldLabel: 'operation.title',
                                    name: 'operation.title',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'commonworkstationcombo'
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    fieldLabel: 'workstation.title',
                                    name: 'workstation.title'
                                },
                                {
                                    xtype: 'commonsuppliercombo'
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    fieldLabel: 'supplier.title',
                                    name: 'supplier.title'
                                }
                            ]
                        })
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processForm: function(config) {
        return Utilities.processConfigBundle(config, 'batchRoute');
    }

});