/*
 * File: app/view/CommonCreateBtn.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.view.CommonCreateBtn', {
    extend: 'Ext.button.Button',
    alias: 'widget.commoncreatebtn',

    itemId: 'commonCreateBtn',
    style: 'font-family:Pictos;',
    glyph: 43,
    text: 'Create',

    initComponent: function() {
        var me = this;

        me.processCommonCreateBtn(me);
        me.callParent(arguments);
    },

    processCommonCreateBtn: function(config) {

        config.text=Utilities.getMsg('common.createBtn.label');

        return config;
    }

});