/*
 * File: app/view/CommonItemCombo.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.view.CommonItemCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.commonitemcombo',

    itemId: 'commonItemCombo',
    fieldLabel: 'Item.name',
    name: 'item.id',
    displayField: 'name',
    forceSelection: true,
    minChars: 0,
    queryParam: 'nameLike',
    store: 'ItemStore',
    valueField: 'id',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                select: {
                    fn: me.onCommonItemComboSelect,
                    scope: me
                },
                render: {
                    fn: me.onCommonItemComboRender,
                    scope: me
                }
            }
        });

        me.processCommonItemCombo(me);
        me.callParent(arguments);
    },

    processCommonItemCombo: function(config) {
        config.fieldLabel=Utilities.getMsg('item.name.label');

        return config;
    },

    onCommonItemComboSelect: function(combo, records, eOpts) {
        if(combo.up() && combo.up().getForm()){
            combo.up().getForm().setValues({

                'item.title':records[0].data['title'],
                'item.spec':records[0].data['spec'],
                'item.unit':records[0].data['unit'],
                'item.description':records[0].data['description']
            });
        }
    },

    onCommonItemComboRender: function(component, eOpts) {
        component.getStore().load();
    }

});