/*
 * File: app/view/CommonEditorToolbar.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.view.CommonEditorToolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.commoneditortoolbar',

    requires: [
        'foodprint.view.CommonCreateBtn',
        'foodprint.view.CommonDeleteBtn',
        'foodprint.view.CommonSaveBtn',
        'foodprint.view.CommonUpdateBtn'
    ],

    itemId: 'commonEditorToolbar',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'commoncreatebtn',
                    listeners: {
                        click: {
                            fn: me.onCommonCreateBtnClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'commondeletebtn',
                    disabled: true,
                    listeners: {
                        click: {
                            fn: me.onCommonDeleteBtnClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'commonsavebtn',
                    disabled: true,
                    listeners: {
                        click: {
                            fn: me.onCommonSaveBtnClick,
                            scope: me
                        }
                    }
                },
                {
                    xtype: 'commonupdatebtn',
                    disabled: true,
                    listeners: {
                        click: {
                            fn: me.onCommonUpdateBtnClick,
                            scope: me
                        }
                    }
                }
            ]
        });

        me.callParent(arguments);
    },

    onCommonCreateBtnClick: function(button, e, eOpts) {

        this.down('button[itemId=commonDeleteBtn]').setDisabled(true);
        //調整為各自驗證資料格式正確後才允許儲存
        //this.down('button[itemId=commonSaveBtn]').setDisabled(false);
        this.down('button[itemId=commonUpdateBtn]').setDisabled(true);
    },

    onCommonDeleteBtnClick: function(button, e, eOpts) {
        this.down('button[itemId=commonDeleteBtn]').setDisabled(true);
        this.down('button[itemId=commonUpdateBtn]').setDisabled(true);
    },

    onCommonSaveBtnClick: function(button, e, eOpts) {
        this.down('button[itemId=commonSaveBtn]').setDisabled(true);
    },

    onCommonUpdateBtnClick: function(button, e, eOpts) {
        this.down('button[itemId=commonDeleteBtn]').setDisabled(true);
        this.down('button[itemId=commonUpdateBtn]').setDisabled(true);
    }

});