/*
 * File: app/view/CommonWarehouseCombo.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.view.CommonWarehouseCombo', {
    extend: 'Ext.form.field.ComboBox',
    alias: 'widget.commonwarehousecombo',

    itemId: 'commonWarehouseCombo',
    fieldLabel: 'warehouse.name',
    name: 'warehouse.id',
    displayField: 'name',
    forceSelection: true,
    minChars: 0,
    queryParam: 'nameLike',
    store: 'WarehouseStore',
    valueField: 'id',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            listeners: {
                render: {
                    fn: me.onCommonWarehouseComboRender,
                    scope: me
                },
                select: {
                    fn: me.onCommonWarehouseComboSelect,
                    scope: me
                },
                change: {
                    fn: me.onCommonWarehouseComboChange,
                    scope: me
                }
            }
        });

        me.processCommonWarehouseCombo(me);
        me.callParent(arguments);
    },

    processCommonWarehouseCombo: function(config) {
        config.fieldLabel=Utilities.getMsg('warehouse.name.label');

        return config;
    },

    onCommonWarehouseComboRender: function(component, eOpts) {
        component.getStore().load();
    },

    onCommonWarehouseComboSelect: function(combo, records, eOpts) {
        if(combo.up() && combo.up() instanceof Ext.form.Panel && combo.up().getForm()){
            combo.up().getForm().setValues({
                'warehouse.title':records[0].data['title']
            });
        }

        var wlcombo = combo.up().down('commonwarehouselocationcombo');

        if(wlcombo){
            wlcombo.getStore().load({
                params:{'warehouse.id': records[0].data['id']}
            });
            wlcombo.setReadOnly(false);  
        }

    },

    onCommonWarehouseComboChange: function(field, newValue, oldValue, eOpts) {
        if (newValue == null) {
            field.reset();
            if(field.up() && field.up() instanceof Ext.form.Panel && field.up().getForm()){
                field.up().getForm().setValues({
                    'warehouse.title':null,
                    'warehouseLocation.id':null,
                    'warehouseLocation.title':null
                });
            }
        }
    }

});