/*
 * File: app/view/ErpMaterialSheetGrid.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.view.ErpMaterialSheetGrid', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.erpmaterialsheetgrid',

    itemId: 'erpMaterialSheetGrid',
    store: 'ErpMaterialSheetStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    width: 360,
                    displayInfo: true,
                    store: 'ErpMaterialSheetStore'
                }
            ],
            columns: [
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'id',
                    text: 'id',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'typeName',
                    text: 'typeName',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'name',
                    text: 'name',
                    flex: 1
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'workstation.id',
                    text: 'workstation.id',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'workstation.name',
                    text: 'workstation.name',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'workstation.title',
                    text: 'workstation.title',
                    flex: 1
                },
                {
                    xtype: 'numbercolumn',
                    hidden: true,
                    dataIndex: 'supplier.id',
                    text: 'supplier.id',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'supplier.name',
                    text: 'supplier.name',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'supplier.title',
                    text: 'supplier.title',
                    flex: 1
                }
            ],
            listeners: {
                afterrender: {
                    fn: me.onErpMaterialSheetGridAfterRender,
                    scope: me
                }
            }
        });

        me.processErpMaterialSheetGrid(me);
        me.callParent(arguments);
    },

    processErpMaterialSheetGrid: function(config) {
        return Utilities.createFiltersFeature(Utilities.processConfigBundle(config, 'materialSheet'));
    },

    onErpMaterialSheetGridAfterRender: function(component, eOpts) {
        component.getStore().load();
    }

});