/*
 * File: app/view/ErpSaleReturnSheetView.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.view.ErpSaleReturnSheetView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.erpsalereturnsheetview',

    requires: [
        'foodprint.view.ErpSaleReturnSheetGrid',
        'foodprint.view.CommonCustomerCombo',
        'foodprint.view.CommonSelectBtn',
        'foodprint.view.CommonCancelBtn',
        'foodprint.view.CommonWarehouseCombo',
        'foodprint.view.CommonWarehouseLocationCombo',
        'foodprint.view.ErpSaleSheetGrid',
        'foodprint.view.ErpSaleSheetDetGrid',
        'foodprint.view.CommonIndexToolbar',
        'foodprint.view.CommonShowToolbar'
    ],

    layout: {
        type: 'card'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commonindextoolbar'
                    },
                    itemId: 'index',
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'erpsalereturnsheetgrid',
                            itemId: 'grid'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commonshowtoolbar'
                    },
                    itemId: 'show',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        me.processForm({
                            xtype: 'form',
                            flex: 1,
                            itemId: 'form',
                            autoScroll: true,
                            layout: {
                                align: 'stretch',
                                padding: 10,
                                type: 'vbox'
                            },
                            title: '',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    hidden: true,
                                    fieldLabel: 'id',
                                    name: 'id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'typeName',
                                    name: 'typeName',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'name',
                                    name: 'name',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'commoncustomercombo'
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    fieldLabel: 'Customer.title',
                                    name: 'customer.title'
                                },
                                {
                                    xtype: 'datefield',
                                    disabled: true,
                                    fieldLabel: '單據日期',
                                    name: 'dateCreated',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    fieldLabel: '簽核狀態',
                                    name: '',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'panel',
                                    border: false,
                                    itemId: 'collaspe2',
                                    padding: '',
                                    layout: {
                                        autoWidth: false,
                                        titleCollapse: false,
                                        hideCollapseTool: false,
                                        collapseFirst: true,
                                        animate: false,
                                        sequence: false,
                                        activeOnTop: false,
                                        type: 'accordion'
                                    },
                                    bodyBorder: false,
                                    animCollapse: false,
                                    collapseFirst: false,
                                    hideCollapseTool: true,
                                    titleCollapse: true,
                                    items: [
                                        {
                                            xtype: 'form',
                                            border: false,
                                            padding: '',
                                            defaults: {
                                                anchor: '100%'
                                            },
                                            layout: {
                                                align: 'stretch',
                                                padding: 5,
                                                type: 'vbox'
                                            },
                                            bodyPadding: '',
                                            collapsed: false,
                                            collapsible: false,
                                            title: '交易資料',
                                            items: [
                                                {
                                                    xtype: 'datefield',
                                                    itemId: 'accountDate',
                                                    padding: '',
                                                    fieldLabel: '退貨日期',
                                                    name: 'accountDate'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: '部門代號',
                                                    name: 'currency',
                                                    allowBlank: false,
                                                    displayField: 'currencyName',
                                                    store: 'CurrencyStore',
                                                    valueField: 'rate'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: '業務人員',
                                                    name: 'currency',
                                                    allowBlank: false,
                                                    displayField: 'currencyName',
                                                    store: 'CurrencyStore',
                                                    valueField: 'rate'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    flex: 1,
                                                    fieldLabel: '幣別',
                                                    name: 'currency',
                                                    allowBlank: false,
                                                    displayField: 'currencyName',
                                                    store: 'CurrencyStore',
                                                    valueField: 'rate'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    itemId: 'rate',
                                                    fieldLabel: '匯率',
                                                    name: 'rate',
                                                    allowBlank: false
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'subamounts',
                                                    padding: '',
                                                    width: 150,
                                                    fieldLabel: '退貨金額',
                                                    name: 'subamounts',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'tax',
                                                    padding: '',
                                                    width: 150,
                                                    fieldLabel: '退貨稅額',
                                                    name: 'tax',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    itemId: 'totalAmount',
                                                    padding: '',
                                                    width: 150,
                                                    fieldLabel: '合計',
                                                    name: 'totalAmount',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'form',
                                            border: false,
                                            padding: 3,
                                            layout: {
                                                align: 'stretch',
                                                padding: '',
                                                type: 'vbox'
                                            },
                                            bodyPadding: '',
                                            collapsed: false,
                                            collapsible: false,
                                            title: '收貨資料'
                                        },
                                        {
                                            xtype: 'form',
                                            border: false,
                                            padding: '',
                                            layout: {
                                                align: 'stretch',
                                                padding: 5,
                                                type: 'vbox'
                                            },
                                            bodyPadding: '',
                                            collapsed: false,
                                            collapsible: false,
                                            title: '發票資料',
                                            items: [
                                                {
                                                    xtype: 'fieldcontainer',
                                                    disabled: true,
                                                    itemId: '',
                                                    layout: {
                                                        align: 'stretch',
                                                        type: 'hbox'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'numberfield',
                                                            hidden: true,
                                                            name: '',
                                                            readOnly: true
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: '稅別碼',
                                                            name: '',
                                                            readOnly: true
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            name: '',
                                                            readOnly: true
                                                        },
                                                        {
                                                            xtype: 'textfield',
                                                            fieldLabel: '發票聯數',
                                                            name: '',
                                                            readOnly: true
                                                        },
                                                        {
                                                            xtype: 'commonselectbtn',
                                                            margins: '1'
                                                        },
                                                        {
                                                            xtype: 'commoncancelbtn',
                                                            frame: false,
                                                            glyph: 0,
                                                            margins: '1'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    padding: '',
                                                    width: 250,
                                                    fieldLabel: '發票號碼'
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    itemId: 'Date',
                                                    padding: '',
                                                    fieldLabel: '申報年月',
                                                    name: ''
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    padding: '',
                                                    width: 250,
                                                    fieldLabel: '課稅別',
                                                    name: ''
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: '營業稅率',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'datefield',
                                                    padding: '',
                                                    width: 250,
                                                    fieldLabel: '發票日期'
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    fieldLabel: '公司名稱',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'displayfield',
                                                    padding: '',
                                                    width: 250,
                                                    fieldLabel: '統一編號'
                                                },
                                                {
                                                    xtype: 'combobox',
                                                    fieldLabel: '通關方式',
                                                    readOnly: true
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }),
                        {
                            xtype: 'panel',
                            tbar: {
                                xtype: 'commonindextoolbar'
                            },
                            flex: 1,
                            itemId: 'indexDetail',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                me.processDetailGrid({
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    itemId: 'detailGrid',
                                    autoScroll: true,
                                    title: 'ErpSaleReturnSheetDet',
                                    store: 'ErpSaleReturnSheetDetStore',
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'id',
                                            text: 'Id',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'typeName',
                                            text: 'TypeName',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            hidden: true,
                                            dataIndex: 'name',
                                            text: 'Name',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'sequence',
                                            text: 'Sequence',
                                            flex: 1,
                                            format: '0,000'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'warehouse.id',
                                            text: 'Warehouse.id',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'saleSheetDet.id',
                                            text: 'SaleSheet.id',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'saleSheetDet.name',
                                            text: 'SaleSheetDet.name',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'warehouse.name',
                                            text: 'Warehouse.name',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'warehouse.title',
                                            text: 'Warehouse.title',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'warehouseLocation.id',
                                            text: 'WarehouseLocation.id',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'warehouseLocation.name',
                                            text: 'WarehouseLocation.name',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'warehouseLocation.title',
                                            text: 'WarehouseLocation.title',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'batch.name',
                                            text: 'Batch.id',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'batch.name',
                                            text: 'Batch.name',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'item.id',
                                            text: 'Item.id',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'item.name',
                                            text: 'Item.name',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'item.title',
                                            text: 'Item.title',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'qty',
                                            text: 'qty',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'price',
                                            text: '單價',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'subamounts',
                                            text: '貨款',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'tax',
                                            text: '稅額',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'totalAmount',
                                            text: '合計金額',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'customerOrderDet.id',
                                            text: 'CustomerOrderDet.id',
                                            flex: 1
                                        }
                                    ],
                                    listeners: {
                                        beforerender: {
                                            fn: me.onGridBeforeRender1,
                                            scope: me
                                        }
                                    }
                                })
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commonshowtoolbar'
                    },
                    itemId: 'showDetail',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        me.processDetailForm({
                            xtype: 'form',
                            flex: 1,
                            itemId: 'detailForm',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            bodyPadding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    hidden: true,
                                    fieldLabel: 'saleReturnSheet.id',
                                    name: 'saleReturnSheet.id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'numberfield',
                                    hidden: true,
                                    fieldLabel: 'id',
                                    name: 'id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'typeName',
                                    name: 'typeName',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'name',
                                    name: 'name',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'numberfield',
                                    fieldLabel: 'sequence',
                                    name: 'sequence',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    itemId: 'saleSheetDetContainer',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            hidden: true,
                                            fieldLabel: 'saleSheetDet.id',
                                            name: 'saleSheetDet.id',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'SaleSheetDet.sheetNum',
                                            name: 'saleSheetDet.typeName',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            name: 'saleSheetDet.name',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            name: 'saleSheetDet.sequence',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'commonselectbtn',
                                            margins: '1'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'commonwarehousecombo'
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    fieldLabel: 'Warehouse.title',
                                    name: 'warehouse.title'
                                },
                                {
                                    xtype: 'commonwarehouselocationcombo'
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    fieldLabel: 'WarehouseLocation.title',
                                    name: 'warehouseLocation.title'
                                },
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    hidden: true,
                                    fieldLabel: 'id',
                                    name: 'item.id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Item.name',
                                    name: 'item.name',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Item.title',
                                    name: 'item.title',
                                    readOnly: true
                                },
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    hidden: true,
                                    fieldLabel: 'id',
                                    name: 'batch.id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Batch.name',
                                    name: 'batch.name',
                                    readOnly: true
                                },
                                {
                                    xtype: 'numberfield',
                                    fieldLabel: 'qty',
                                    name: 'qty'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '單價',
                                    name: 'price'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '稅額',
                                    name: 'tax'
                                }
                            ]
                        })
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'saleSheetDetIndex',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'erpsalesheetgrid',
                            flex: 1
                        },
                        {
                            xtype: 'erpsalesheetdetgrid',
                            flex: 1
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processForm: function(config) {
        return Utilities.processConfigBundle(config, 'saleReturnSheet');
    },

    processDetailGrid: function(config) {
        return Utilities.processConfigBundle(config, 'saleReturnSheetDet');
    },

    processDetailForm: function(config) {
        return Utilities.processConfigBundle(config, 'saleReturnSheetDet');
    },

    onGridBeforeRender1: function(component, eOpts) {
        component.getStore().removeAll();
    }

});