/*
 * File: app/view/ForwardTraceTreeView.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.view.ForwardTraceTreeView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.forwardtracetreeview',

    requires: [
        'foodprint.view.TraceTree',
        'foodprint.view.TraceSheetGrid',
        'foodprint.view.CommonBackBtn',
        'foodprint.view.CommonTraceToolbar'
    ],

    layout: {
        type: 'card'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commontracetoolbar',
                        width: 100
                    },
                    itemId: 'treeDiagram',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'tracetree',
                            flex: 1,
                            itemId: 'tree',
                            store: 'ForwardTraceTreeStore'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'toolbar',
                        items: [
                            {
                                xtype: 'commonbackbtn'
                            }
                        ]
                    },
                    itemId: 'sheetDetail',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'tracesheetgrid',
                            flex: 1,
                            itemId: 'sheetGrid'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});