/*
 * File: app/view/ReceivableSheet.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.view.ReceivableSheet', {
    extend: 'Ext.panel.Panel',

    requires: [
        'foodprint.view.ErpSaleSheetGrid',
        'foodprint.view.CommonCustomerCombo',
        'foodprint.view.CommonSelectBtn',
        'foodprint.view.ErpCustomerOrderGrid',
        'foodprint.view.ErpCustomerOrderDetGrid',
        'foodprint.view.CommonIndexToolbar',
        'foodprint.view.CommonShowToolbar'
    ],

    layout: {
        type: 'card'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commonindextoolbar'
                    },
                    itemId: 'index',
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'erpsalesheetgrid',
                            itemId: 'grid'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commonshowtoolbar'
                    },
                    itemId: 'show',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        me.processForm({
                            xtype: 'form',
                            flex: 1,
                            itemId: 'form',
                            autoScroll: true,
                            layout: {
                                align: 'stretch',
                                padding: 10,
                                type: 'vbox'
                            },
                            title: '',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    hidden: true,
                                    fieldLabel: 'id',
                                    name: 'id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'typeName',
                                    name: 'typeName',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'name',
                                    name: 'name',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'commoncustomercombo'
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    fieldLabel: 'Customer.title',
                                    name: 'customer.title'
                                },
                                {
                                    xtype: 'datefield',
                                    disabled: true,
                                    fieldLabel: '單據日期',
                                    name: 'dateCreated',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    disabled: true,
                                    fieldLabel: '簽核狀態',
                                    name: '',
                                    allowBlank: false
                                }
                            ]
                        }),
                        {
                            xtype: 'panel',
                            tbar: {
                                xtype: 'commonindextoolbar'
                            },
                            flex: 1,
                            itemId: 'indexDetail',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            items: [
                                me.processDetailGrid({
                                    xtype: 'gridpanel',
                                    flex: 1,
                                    itemId: 'detailGrid',
                                    autoScroll: true,
                                    title: 'ErpReceivableSheetDet',
                                    store: 'ErpSaleSheetDetStore',
                                    columns: [
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'id',
                                            text: 'Id',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            dataIndex: 'sequence',
                                            text: 'Sequence',
                                            flex: 1,
                                            format: '0,000'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: '借/貸',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: '類別',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'name',
                                            text: '來源單別',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            enableColumnHide: false,
                                            dataIndex: 'typeName',
                                            hideable: false,
                                            text: '來源單號',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            enableColumnHide: false,
                                            dataIndex: 'typeName',
                                            hideable: false,
                                            text: '會計科目',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            enableColumnHide: false,
                                            dataIndex: 'typeName',
                                            hideable: false,
                                            text: '科目名稱',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            enableColumnHide: false,
                                            dataIndex: 'typeName',
                                            hideable: false,
                                            text: '幣別',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            enableColumnHide: false,
                                            dataIndex: 'typeName',
                                            hideable: false,
                                            text: '部門別',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            enableColumnHide: false,
                                            dataIndex: 'typeName',
                                            hideable: false,
                                            text: '部門名稱',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            enableColumnHide: false,
                                            dataIndex: 'typeName',
                                            hideable: false,
                                            text: '匯率',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'tax',
                                            text: '稅額',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'subamounts',
                                            text: '貨款',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'totalAmount',
                                            text: '合計金額',
                                            flex: 1
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            hidden: true,
                                            dataIndex: 'customerOrderDet.id',
                                            text: 'CustomerOrderDet.id',
                                            flex: 1
                                        }
                                    ],
                                    listeners: {
                                        beforerender: {
                                            fn: me.onGridBeforeRender1,
                                            scope: me
                                        }
                                    }
                                })
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commonshowtoolbar'
                    },
                    itemId: 'showDetail',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        me.processDetailForm1({
                            xtype: 'form',
                            flex: 1,
                            itemId: 'detailForm1',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            bodyPadding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    flex: 1,
                                    hidden: true,
                                    fieldLabel: 'accountSheet.id',
                                    name: 'accountSheet.id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'numberfield',
                                    hidden: true,
                                    fieldLabel: 'id',
                                    name: 'id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'typeName',
                                    name: 'typeName',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'name',
                                    name: 'name',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'numberfield',
                                    fieldLabel: 'sequence',
                                    name: 'sequence',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'documentSource',
                                    fieldLabel: '借貸方',
                                    name: 'documentSource',
                                    displayField: 'name',
                                    queryMode: 'local',
                                    store: 'DocumentSheetStore',
                                    valueField: 'name'
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'documentSource1',
                                    fieldLabel: '類別',
                                    name: 'documentSource',
                                    displayField: 'name',
                                    queryMode: 'local',
                                    store: 'DocumentSheetStore',
                                    valueField: 'name'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    itemId: 'sourceSheetContainer',
                                    layout: {
                                        align: 'stretch',
                                        type: 'hbox'
                                    },
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            hidden: true,
                                            fieldLabel: 'saleSheetDet.id',
                                            name: 'sourceDocumentName',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            fieldLabel: 'sourceSheet.Num',
                                            name: 'documentTypeName',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            name: 'documentName',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            name: 'documentSequence',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'commonselectbtn',
                                            margins: '1'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'documentSource2',
                                    fieldLabel: '會計科目',
                                    name: 'documentSource',
                                    displayField: 'name',
                                    queryMode: 'local',
                                    store: 'DocumentSheetStore',
                                    valueField: 'name'
                                },
                                {
                                    xtype: 'combobox',
                                    itemId: 'documentSource3',
                                    fieldLabel: '會計名稱',
                                    name: 'documentSource',
                                    displayField: 'name',
                                    queryMode: 'local',
                                    store: 'DocumentSheetStore',
                                    valueField: 'name'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '部門別',
                                    name: 'subamounts',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '部門名稱',
                                    name: 'subamounts',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '幣別',
                                    name: 'subamounts',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '匯率',
                                    name: 'subamounts',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '原幣金額',
                                    name: 'subamounts',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '本幣金額',
                                    name: 'tax',
                                    readOnly: true
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: '備註',
                                    name: 'remark',
                                    readOnly: true
                                }
                            ]
                        })
                    ]
                },
                {
                    xtype: 'panel',
                    itemId: 'customerOrderDetIndex',
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'erpcustomerordergrid',
                            flex: 1
                        },
                        {
                            xtype: 'erpcustomerorderdetgrid',
                            flex: 1
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processForm: function(config) {
        return Utilities.processConfigBundle(config, 'saleSheet');
    },

    processDetailGrid: function(config) {

        return Utilities.processConfigBundle(config, 'saleSheetDet');
    },

    processDetailForm1: function(config) {
        return Utilities.processConfigBundle(config, 'accountSheetDet');
    },

    onGridBeforeRender1: function(component, eOpts) {
        component.getStore().removeAll();
    }

});