/*
 * File: app/view/ReportParamsView.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('foodprint.view.ReportParamsView', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.reportparamsview',

    requires: [
        'foodprint.view.ReportGrid',
        'foodprint.view.CommonParamCombo',
        'foodprint.view.CommonOperationCombo',
        'foodprint.view.CommonWorkstationCombo',
        'foodprint.view.CommonSupplierCombo',
        'foodprint.view.CommonItemCombo'
    ],

    itemId: 'reportEditorct',
    autoScroll: true,
    layout: {
        type: 'card'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commonindextoolbar'
                    },
                    itemId: 'index',
                    autoScroll: true,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        {
                            xtype: 'reportgrid',
                            itemId: 'masterGrid',
                            flex: 1
                        },
                        me.processGrid({
                            xtype: 'gridpanel',
                            loadReportParams: function(reportId) {
                                console.log("View-reportParamsGrid.loadReportParams");

                                var store = this.getStore();
                                store.data.clear();
                                store.load({
                                    params:{reportid:reportId}
                                });
                            },
                            flex: 1,
                            itemId: 'grid',
                            autoScroll: true,
                            title: 'ReportParams',
                            store: 'ReportParamsStore',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'report.id',
                                    text: 'report.id',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'report.name',
                                    text: 'report.name',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'param.name',
                                    text: 'param.name',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'param.title',
                                    text: 'param.title',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'operation.name',
                                    text: 'operation.name',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'operation.title',
                                    text: 'operation.title',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'workstation.name',
                                    text: 'workstation.name',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'workstation.title',
                                    text: 'workstation.title',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'supplier.name',
                                    text: 'supplier.name',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'supplier.title',
                                    text: 'supplier.title',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'item.name',
                                    text: 'item.name',
                                    flex: 1
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'item.title',
                                    text: 'item.title',
                                    flex: 1
                                }
                            ],
                            listeners: {
                                beforerender: {
                                    fn: me.onGridBeforeRender,
                                    scope: me
                                }
                            }
                        })
                    ]
                },
                {
                    xtype: 'panel',
                    tbar: {
                        xtype: 'commonshowtoolbar'
                    },
                    itemId: 'show',
                    autoScroll: true,
                    layout: {
                        align: 'stretch',
                        type: 'vbox'
                    },
                    items: [
                        me.processForm({
                            xtype: 'form',
                            doDisplay: function(record) {
                                console.log("View-batchRouteForm.doDisplay");
                                this.loadRecord(record);
                            },
                            itemId: 'form',
                            layout: {
                                align: 'stretch',
                                type: 'vbox'
                            },
                            bodyPadding: 10,
                            title: '',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Report_id',
                                    name: 'report.id',
                                    readOnly: true,
                                    allowBlank: false
                                },
                                {
                                    xtype: 'textfield',
                                    hidden: true,
                                    fieldLabel: 'id',
                                    name: 'id',
                                    readOnly: true
                                },
                                {
                                    xtype: 'commonparamcombo',
                                    allowBlank: false,
                                    flex: 1
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'param.title',
                                    name: 'param.title',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'commonoperationcombo'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'operation.title',
                                    name: 'operation.title',
                                    allowBlank: false
                                },
                                {
                                    xtype: 'commonworkstationcombo'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'workstation.title',
                                    name: 'workstation.title'
                                },
                                {
                                    xtype: 'commonsuppliercombo',
                                    flex: 1
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'supplier.title',
                                    name: 'supplier.title'
                                },
                                {
                                    xtype: 'commonitemcombo',
                                    flex: 1
                                },
                                {
                                    xtype: 'textfield',
                                    flex: 1,
                                    fieldLabel: 'item.title',
                                    name: 'item.title'
                                }
                            ]
                        })
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processGrid: function(config) {
        return Utilities.processConfigBundle(config, 'reportParams');
    },

    processForm: function(config) {
        return Utilities.processConfigBundle(config, 'reportParams');
    },

    onGridBeforeRender: function(component, eOpts) {
        component.getStore().removeAll();
    }

});